### ISSUE TITLE
expandAllChildren causes duplicate tree nodes

### ISSUE THREAD

**Issue by christianrowlands** [embraceitmobile/animated_tree_view#15]
Good evening!

Thank you for creating this project. It has been awesome to use!

I have run into a bug using the new `expandAllChildren` feature released in version 2.0.0. When calling that method on the `TreeViewController`, it creates duplicates of all the items in the tree. I was able to reproduce the issue in your [example Flutter app](https://github.com/embraceitmobile/animated_tree_view/blob/main/example/lib/main.dart).

Here is a screenshot of the problem. Notice that there are two instances of `Item 1-0E`. All I did to get into this state is click the `Expand all` button exactly once. If you click it a few times then the duplicates are cleared out.

![image](https://github.com/embraceitmobile/animated_tree_view/assets/8020686/f4f0a1e9-0b3f-49f6-bf7e-83eace94f502)

**Comment by jawwad-hassan89** [comment]
hi @christianrowlands, thanks for the appreciation and your feedback.
I will look into this issue, and fix it.

**Comment by berslen** [comment]
> hi @christianrowlands, thanks for the appreciation and your feedback. I will look into this issue, and fix it.

Same issue with expand as well, And please add example for best practice to get tree controller.

**Comment by christianrowlands** [comment]
Yeah, that is another issue I am running into. I can get the controller, but it is not initialized until after the `initState()` and `build()` methods are called. As a result, I am not sure when to expand all the children. I am using your library to display comments on a post, and I want the comments to always be expanded. I have tried a variety of options but am unable to figure out how to expand all without adding some sort of delayed timer that is called so that the lazy initialized controller is ready.

**Comment by jawwad-hassan89** [comment]
@christianrowlands I didn't such a use case in mind when I designed the controller, and with the current implementation I don't see any way of getting to know when the controller will get initialized, so the a delayed seems like the best option.
Just an FYI, thee controller is initialized in the `initState` method of the `TreeView`, so it takes some time to initialize.

What I can do, is to add a `onTreeReady` callback to the `TreeView` which will provide the controller. This way the controller will also be more straight-forward to access rather than using the `GlobalKey` to get the controller.

Will this work for you @christianrowlands ?

**Comment by jawwad-hassan89** [comment]
@berslen I will look into the `Expand` method as well, will hopefully have a fix ready by tomorrow.

**Comment by christianrowlands** [comment]
Yeah, an `onTreeReady` callback would be great.

Or maybe there is an even more straightforward approach for my specific use case. I am looking to mimic Reddit's behavior for comments on a post where all of the comments and child comments are expanded by default. Given the new `expandAllChildren` method that was added, I thought that was the best option. But if there were a way to set the default expansion state of a node, then I could override the `TreeNode` class and set the expansion state to true. Something like this?

```
/// Represents a Comment that is submitted to/received from the server backend.
class Comment extends TreeNode {
  final String commentId;
  final String? parentId; // Null indicates a top level comment
  final String postId;
  final String userId;
  final String comment;
  DateTime? createdAt;

  Comment({
    required this.commentId,
    this.parentId,
    required this.postId,
    required this.userId,
    required this.comment,
    this.createdAt,
  }) : super(key: commentId, initialExpansionState: true);
}
```

**Comment by jawwad-hassan89** [comment]
@christianrowlands you can already use the `TreeNode..expansionNotifier.value` to set the initial expansion state, but right now it won't have any effect as the initial state is always collapsed for the `TreeNode`.
I will do some refactoring so that the initial expansion state is respected by the `TreeNode`. 

`onTreeReady` callback will be easy to implement, this might take a little longer.

**Comment by jawwad-hassan89** [comment]
the fix for `TreeViewController` `.expand` and `.expandAllChildren` has been pushed to the [fix/treeview-controller](https://github.com/embraceitmobile/animated_tree_view/tree/fix/treeview-controller) branch. 
The `onTreeReady` callback has also been added.

You can use the updated code from this branch, it is working but not properly tested yet. The branch will be merged into `main` after testing and documentation changes.
