### ISSUE TITLE
Custom name for node

### ISSUE THREAD

**Issue by Salman3sh** [embraceitmobile/animated_tree_view#4]
Hi,

Currently when adding a new child or node, it is adding a name based on level and key. 

What about adding a custom name? Is there any sample for this matter. I am trying to open a dialog to read the name and then I changed the code, but I am receiving some errors.

**Comment by jawwad-hassan89** [comment]
HI Salman,
I have added an example for using a custom object with TreeNode [here](https://github.com/embraceitmobile/animated_tree_view/blob/main/example/lib/samples/treeview_custom_object_sample.dart)

Basically, you will need to wrap the the CustomClass in TreeNode like `TreeNode<CustomClass>`, and use one of the typed constructors e.g.`TreeView.simpleTyped<CustomClass, TreeNode<CustomClass>>` instead of the simple constructors, as this allows the linter to correctly identify the class type in the builder.

Now you can access your object in the builder like this: `builder: (context, level, item) => item.someFieldInCustomClass`
